[build]
  publish = "_site"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "https://insight.bravery.co/*"
  to = "https://bravery.co/insight/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://speedy.bravery.co/*"
  to = "https://speedyu.bravery.co/"
  force = true

[[redirects]]
  from = "/contented18"
  to = "https://speakerdeck.com/joelgoodman/content-first-design-what-does-it-really-mean-and-how-can-it-enhance-the-audience-experience"
  status = 200

[[redirects]]
  from = "/about"
  to = "/services/"
  status = 301

[[redirects]]
  from = "/survey"
  to = "https://www.surveymonkey.com/r/webstrategytrends2024"
  status = 302

[[redirects]]
  from = "/services/level-up/"
  to = "https://bravery.co/services/web-aor/"
  status = 301

[[redirects]]
  from= "/services/custom-insights/"
  to = "https://bravery.co/services/website-strategy/"
  status = 301

[[redirects]]
  from = "/insight/higher-ed-website-redesign-small-team"
  to = "https://bravery.co/insight/case-study/national-university-web-strategy/"
  status = 301

[[redirects]]
  from = "/insight/higher-ed-website-redesign-small-team/"
  to = "https://bravery.co/insight/case-study/national-university-web-strategy/"
  status = 301

[[redirects]]
  from = "/speedyu-turbo/"
  to = "https://bravery.co/benchmark/"
  status = 302

[[redirects]]
  from = "/insight/case-studies/"
  to = "https://bravery.co/work/"
  status = 301

[[headers]]
  for = "/*"

[headers.values]
  Cache-Control = "public, max-age=31536000"
